#if !canImport(ObjectiveC)
import XCTest

extension PusherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PusherTests = [
        ("testGetChannels", testGetChannels),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PusherTests.__allTests__PusherTests),
    ]
}
#endif
