#if !canImport(ObjectiveC)
import XCTest

extension PusherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PusherTests = [
        ("testGetChannelInfoFailsForInvalidAttributes", testGetChannelInfoFailsForInvalidAttributes),
        ("testGetChannelInfoSucceeds", testGetChannelInfoSucceeds),
        ("testGetChannelsFailsForInvalidAttributes", testGetChannelsFailsForInvalidAttributes),
        ("testGetChannelsSucceeds", testGetChannelsSucceeds),
        ("testGetUsersForChannelFailsForPublicChannel", testGetUsersForChannelFailsForPublicChannel),
        ("testGetUsersForChannelSucceedsForPresenceChannel", testGetUsersForChannelSucceedsForPresenceChannel),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PusherTests.__allTests__PusherTests),
    ]
}
#endif
